name: Deploy Pages on Main Branch Push

on:
  push:
    branches:
      - main

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Deploy Pages
        run: pnpm run pages:deploy
